name: DEEP_MutOnco

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10  
  - pip
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pytorch>=2.3
  - torchaudio>=2.3
  - pytorch-cuda=12.1
  - pip:
      - pytorch-lightning>=2.0.0  
      - tensorboardX  
      - pytorchtools  
      - tensorflow==2.13.0  
      - opencv-python
      - fastapi
      - uvicorn
      - requests
      - h5py
      - jupyterlab
      - ipython
      - ipykernel
      - optuna
      - shap