name: Deep-GV-utOnco

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10  
  - pip
  - numpy=1.24.3
  - scipy=1.10.1
  - pandas=1.5.3
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pytorch>=2.3
  - torchaudio>=2.3
  - pytorch-cuda=12.1
  - networkx
  - pip:
      - pytorch-lightning>=2.0.0  
      - tensorboardX  
      - pytorchtools  
      - tensorflow==2.13.0  
      - opencv-python
      - fastapi
      - uvicorn
      - requests
      - h5py
      - jupyterlab
      - ipython
      - ipykernel
      - optuna
      - shap
      - lifelines==0.27.4
      - autograd==1.5
